version: '3.9'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    environment:
      AUTH_SERVICE_URL: http://auth-service:8000
      SCRAPER_SERVICE_URL: http://scraper-service:8000/scrape
      # ANALYSIS_SERVICE_URL removed since analysis-service is not defined
    depends_on:
      - auth-service
      - scraper-service
    networks:
      - internal

  auth-service:
    build: ./auth-service
    ports:
      - "8001:8000"
    environment:
      OAUTH_AUTHORIZE_URL: https://accounts.google.com/o/oauth2/v2/auth
      OAUTH_TOKEN_URL: https://oauth2.googleapis.com/token
      OAUTH_REDIRECT_URI: http://localhost:8001/callback
      OAUTH_CLIENT_ID_FILE: /run/secrets/oauth_client_id
      OAUTH_CLIENT_SECRET_FILE: /run/secrets/oauth_client_secret
    secrets:
      - oauth_client_id
      - oauth_client_secret
    networks:
      - internal
  oauth_client_id:
    file: ./secrets/oauth_client_id
  oauth_client_secret:
    file: ./secrets/oauth_client_secret

  scraper-service:
    build: ./scraper-service
    environment:
      SECURE_DATA_SERVICE_URL: http://secure-data-service:8000
      PRIVATE_KEY_PATH: /run/secrets/private_key.pem
      SCRAPER_USERNAME: chrishemsworth
    secrets:
      - private_key.pem
      - scrapfly_key
      scrapfly_key:
        file: ./secrets/scrapfly_key
    depends_on:
      - secure-data-service
    networks:
      - internal

  secure-data-service:
    build: ./secure-data-service
    environment:
      MONGO_URI: mongodb://mongodb:27017
      PUBLIC_KEY_PATH: /run/secrets/public_key.pem
    secrets:
      - public_key.pem
    depends_on:
      - mongodb
    networks:
      - internal

  mongodb:
    image: mongo:6
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - internal
    expose:
      - 27017


secrets:
  private_key.pem:
    file: ./secrets/private_key.pem
  public_key.pem:
    file: ./secrets/public_key.pem

volumes:
  mongo_data:

networks:
  internal:
    driver: bridge
